### ISSUE TITLE
Issue with None optimizations

### ISSUE THREAD

**Issue by mbauman** [bramtayl/JuliennedArrays.jl#1]
I really like this package — and the name is wonderful.  Here's a slight issue I ran into while I was testing it out.  I think it's due to the `None(f)` optimization:

```
julia> A = reshape(1:60, 5,4,3);

julia> map(median, julienne(A, (*, *, :)))
5×4×1 Array{Float64,3}:
[:, :, 1] =
 21.0  0.0  0.0           0.0
 22.0  0.0  0.0           0.0
 23.0  0.0  5.43472e-323  0.0
 24.0  0.0  0.0           0.0
 25.0  0.0  6.42285e-323  0.0

julia> map(sum, julienne(A, (*, *, :)))
5×4×1 Array{Int64,3}:
[:, :, 1] =
 63  78   93  108
 66  81   96  111
 69  84   99  114
 72  87  102  117
 75  90  105  120

julia> map(x->sum(x), julienne(A, (*, *, :)))
5×4×1 Array{Int64,3}:
[:, :, 1] =
 63  1  2  3
 66  2  3  4
 69  3  3  4
 72  2  3  4
 75  2  3  4
```

**Comment by bramtayl** [comment]
Thanks! This package is going to need an overhaul before it makes it into base:

1) it requires type-stable tuple operations (most notably boolean subsetting).
2) this in turn requires typed bools e.g. Val{true/false}(), or extremely aggressive constant folding
3) type stable tuple operations are slow for very large type-constant tuples; @timholy found a way around that here: https://github.com/JuliaLang/julia/pull/23875

So anyway I'd rather not dive back into this until these more basic issues have been resolved.

**Comment by bramtayl** [comment]
Ok when I redid the interface I got rid of a bunch optimizations so this issue disappeared. I'll add back in optimizations for things like median once the interface stabilizes.

**Comment by bramtayl** [comment]
```julia
julia> map(x->sum(x), julienne(Views, A, (*, *, :)))
5×4 Array{Int64,2}:
 63  78   93  108
 66  81   96  111
 69  84   99  114
 72  87  102  117
 75  90  105  120
```
