### ISSUE TITLE
how are docs generated?

### ISSUE THREAD

**Issue by tpapp** [bramtayl/JuliennedArrays.jl#10]
I could not find the code for it in the repo.

OK if I make a PR for the standard Documenter/project based approach?

**Comment by bramtayl** [comment]
It happens in runtests.jl.  I do this on purpose so that doctests run as part of regular testing. I'm pretty convinced this makes a lot sense, and I do it in all of my packages. What do you think?

**Comment by tpapp** [comment]
AFAIK the recommended approach is 

https://discourse.julialang.org/t/psa-use-a-project-for-building-your-docs/14974

I would be very happy to make a PR implementing it.

**Comment by bramtayl** [comment]
Sure! I suspect it will tank coverage, but worth a shot?

**Comment by tpapp** [comment]
OK, I will also add some tests then.

**Comment by bramtayl** [comment]
I'm a bit hesitant about adding redundant tests... I think you'd have to convince me that the new setup is worth it.

**Comment by tpapp** [comment]
I guess the main advantage would be that the actual tests could include things which are not exposed/useful for the user, or are implicitly expected, so they don't end up in docstrings. Eg tests for `@inferred`, constant folding as in #13, etc.

**Comment by bramtayl** [comment]
I think I'd like the `@inferred` example to be included as part of the docstring, so that users could see how to use the new feature in a type stable way.
