### ISSUE TITLE
suggestion: Dims(...) for expanding into (True(),False(),...)

### ISSUE THREAD

**Issue by tpapp** [bramtayl/JuliennedArrays.jl#13]
I was thinking of a syntax like
```julia
Slices(A, Dims(1,3))
```
which would expand to
```julia
Slices(A, True(),False(),True(),...)
```
of course depending on the dimensionality of `A`. Similarly for `Align`.

Happy to make a PR, just wanted to see what you think about it.

**Comment by tpapp** [comment]
Good point about the syntax. Yes, I will make sure everything is inferred under 1.1.

**Comment by bramtayl** [comment]
Done
