### ISSUE TITLE
Provide a default Parts method for `julienne`

### ISSUE THREAD

**Issue by mbauman** [bramtayl/JuliennedArrays.jl#4]
I think it'd be okay — advantageous in fact — to just be opinionated and provide a default method for `julienne`'s slicing.  This should be able to be done unambiguously with your current  `julienne` method.  I think I'd just pick `View` as the default, but I'm not sure it matters much which — if your favorite is different I say document it and go with that.

What would you think?

**Comment by bramtayl** [comment]
The danger with `View` is that it would allow functions to mutate the underlying array. I still think I like `View` best though.

**Comment by bramtayl** [comment]
Ok, i pushed a version of master where `Views` is now the default.
