### ISSUE TITLE
Recoverable type weirdness with deep stack trace

### ISSUE THREAD

**Issue by chelate** [bramtayl/JuliennedArrays.jl#6]
First I want to say that I LOVE this package, and the sooner it's in base, the better.

I'm therefore honoured to open up an issue involving julienning arrays of mixed type. This is also my first github issue ever so let me know if I'm doing it wrong.

`a=[string.(round.(rand(5),sigdigits=2)) round.(rand(5,5),sigdigits=2)]
for x in julienne(a,(*,:))
       print(x)
end`

results in 

> Internal error: encountered unexpected error in runtime:
> TypeError(func=:<:, context="", expected=Type{T} where T, got=A)
> rec_backtrace at /Users/osx/buildbot/slave/package_osx64/build/src/stackwalk.c:94
> record_backtrace at /Users/osx/buildbot/slave/package_osx64/build/src/task.c:246 [inlined]
> jl_throw at /Users/osx/buildbot/slave/package_osx64/build/src/task.c:577
> jl_type_error_rt at /Users/osx/buildbot/slave/package_osx64/build/src/rtutils.c:118
> jl_type_error at /Users/osx/buildbot/slave/package_osx64/build/src/rtutils.c:124
> jl_f_issubtype at /Users/osx/buildbot/slave/package_osx64/build/src/builtins.c:407
> ....

deep deep stacktrace
obviously on osx Julia version 1.0.0
edit: also it recovers and prints the right thing.

**Comment by bramtayl** [comment]
Hi. Thanks so much! This seems like a bug in Julia 1.0. The code runs just fine for me on the Windows nightly binary, so I guess they must have fixed it?

**Comment by chelate** [comment]
Hmm yep, by 1.02 the issue is gone.  Thanks.
